version:  '3'
services:
  nextcloud:
     image: "joequant/nextcloud"
     build:
       context: .
       dockerfile: Dockerfile
     ports:
       - 89:80
       - 443:443
     volumes:
       - lib:/var/lib/nextcloud
       - etc:/etc/nextcloud
  db:
      image: postgres:12-alpine
      restart: always
      environment:
       - POSTGRES_PASSWORD:mypass
      volumes:
       - db:/var/lib/pgsql

volumes:
   lib:
   db:
   etc:
