version:  '3'
services:
  bitstation:
     image: "joequant/bitstation"
     build:
       context: 02.setup
       dockerfile: Dockerfile
       args:
          base: "joequant/cauldron"
     stdin_open: true
     tty: true
     ports:
       - 89:80
       - 443:443
     volumes:
       - home:/home
       - dokuwiki:/var/lib/dokuwiki
       - mongodb:/var/lib/mongodb
       - redis:/var/lib/redis
       - bitcoin:/var/lib/bitcoin
       - log:/var/log
       - etc:/etc
       - srv:/srv
  cauldron:
     image: "joequant/cauldron"
     build: 01.cauldron
     entrypoint: ["echo", "Service cauldron disabled"]
  nextcloud:
     image: "joequant/nextcloud"
     build:
       context: .
       dockerfile: Dockerfile
     volumes:
       - lib:/var/lib/nextcloud
       - etc-nextcloud:/etc/nextcloud
     restart: always
     depends_on:
       - db
  db:
      image: postgres:12-alpine
      restart: always
      environment:
       - POSTGRES_PASSWORD:mypass
      volumes:
       - db:/var/lib/postgresql/data
      restart: always

volumes:
   home:
   dokuwiki:
   mongodb:
   redis:
   bitcoin:
   log:
   etc:
   srv:
   lib:
   etc-nextcloud:
   db:
