version:  '3'
services:
  bitstation:
     image: "joequant/bitstation"
     build:
       context: 03.setup
       dockerfile: Dockerfile
       args:
          base: "joequant/pkgs:cauldron"
     stdin_open: true
     tty: true
     ports:
       - 80:80
       - 443:443
     volumes:
       - home:/home
       - dokuwiki:/var/lib/dokuwiki
       - mongodb:/var/lib/mongodb
       - redis:/var/lib/redis
       - bitcoin:/var/lib/bitcoin
       - log:/var/log
       - etc:/etc
       - srv:/srv
  pkgs-cauldron:
     image: "joequant/pkgs:cauldron"
     build:
       context: 02.pkgs
       dockerfile: Dockerfile
       args:
          base: joequant/cauldron
  pkgs-7:
     image: "joequant/pkgs:7"
     build:
       context: 02.pkgs
       dockerfile: Dockerfile
       args:
         base: mageia:7
  cauldron:
     image: "joequant/cauldron"
     build: 01.cauldron

volumes:
   home:
   dokuwiki:
   mongodb:
   redis:
   bitcoin:
   log:
   etc:
   srv:
