version:  '3'
services:
   ldap:
     image: "joequant/ldap"
     ports:
       - 3389:389
       - 9091:9090
     volumes:
       - spool:/var/spool
       - log:/var/log

volumes:
      spool:
      log:
